version: "3.8"

services:
    app-db:
        image: mysql
        container_name: app-db
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: spring
